### PR TITLE
Fix hybrid=3 blending with wrong frame

### PR DESCRIPTION
**Pull request by flossy83**
See https://forum.doom9.org/showpost.php?p=1996299&postcount=76

The changes only affect hybrid=3 mode

### CODE REVIEW

**Comment by pinterf** [comment]
You wrote that this behavior was intentional,
"_But it has some kind of bug or intentional behaviour which makes it blend with the wrong frame,_"

Now that you are better in the topic, can you imagine that using `<` instead of `<=` (and vica versa) was an intentional move?

**Comment by flossy83** [comment]
I presume bugs are unintentional, so really what I meant to say was either it was unintentional or intentional.

I don't know if it's intentional or not, I guess only Tritical would know (assuming he wrote that function?)

I don't really understand every line of CalcBlendRatios2, I'm just making an educated guess and seeing what comes out of the black box, and what comes out is what I think it should be doing haha

I'm really bad at reading other people's code, to me it's like trying to do decompiling in my head.  Without meaningful comments it makes it even harder.

**Comment by flossy83** [comment]
But to answer your question if I had to bet on it I'd probably say it is a bug, cause even with the default cycle=5 it still sometimes blends a bit with 2 frames ahead on the clock test pattern.

**Comment by pinterf** [comment]
Thanks for the explanation.

**Pull request merged**
